link1: "https://screencasts.railstutorial.org/"
link2: "https://www.railstutorial.org/book"
link3: "https://www.learnenough.com/"
link4: "https://www.learnenough.com/"
link5: "https://rubyonrails.org/"
link6: "https://www.railstutorial.org/"
link7: "https://www.railstutorial.org/contact"
link8: "https://www.railstutorial.org/help"
link9: "https://www.railstutorial.org/book"
link10: "http://news.railstutorial.org/"
link11: "http://www.michaelhartl.com/"
image1: "rails.png"
name_in_users_max: 50
email_in_users_max: 255
password_min: 6
size_avatar_default: 80
size_avatar: 100
remember_value: "1"
